### PR TITLE
Revert "Adding documentation"

### PR DESCRIPTION
**Pull request by MaximPerry**
Reverts wet-boew/cdts-sgdc#104

As the _docs folder can't be used with gh-page, we, let's create a new repository instead for the documentation.

### CODE REVIEW

**Comment by duboisp** [comment]
@MaximPerry for the gh-pages the folder need to be name "docs" not "_docs"

For new repository, I can do it.

**Comment by duboisp** [comment]
PS: @MaximPerry FYI - Self merge is a bad practice

**Comment by MaximPerry** [comment]
@duboisp Amazing, thanks. I just sent you an email about it... You can ignore it then.

**Comment by nschonni** [comment]
@duboisp you can disabled self merge through branch policy

**Pull request merged**
